export const queryKeys = {
    grocery: 'groceries',
    groceryAutocomplete: 'groceries-autocomplete',
    familyGroup: 'family-group',
    user: 'users',
    userRecipe: 'user-recipes',
    recipes: 'recipes',
    analytics: 'analytics',
    foodsAutocomplete: 'foods-autocomplete',
    foodNutrients: 'food-nutrients',
    meals: 'meals',
    mealDetails: 'meal-details',
    mealTemplates: 'meal-templates',
    nutritionSummary: 'nutrition-summary',
}
